### ISSUE TITLE
Bad network after a few hundreds of requests?

### ISSUE THREAD

**Issue by urielgolab** [cjvnjde/google-translate-api-browser#11]
Testing with a file contents of less than a thousand sentences, node client started to throw "bad network". 

It seems to me that Google detects this batch unauthorized process and starts to reject requests. 

I can't continue translating since then.

**Comment by NavehMevorach** [comment]
Same

**Comment by mathmed** [comment]
some fix?

**Comment by urielgolab** [comment]
Pay for a license or cache results and do not ask for things that you already did before.
