### ISSUE TITLE
Could you add a POST request from GET for more capacity?

### ISSUE THREAD

**Issue by taishi55** [cjvnjde/google-translate-api-browser#20]
The maximum number of letter seems roughly 1850 per request. 

Is it possible to add a POST request to increase the input text to 5000?

This is my suggestion below. (It didn't work sadly)

```ts
export const traslateToEng = async (sourceText: string): Promise<string> => {
  const queryParams = {
    client: translateOptions.client,
    sl: translateOptions.from,
    tl: translateOptions.to,
    hl: translateOptions.hl,
    ie: 'UTF-8',
    oe: 'UTF-8',
    otf: '1',
    ssel: '0',
    tsel: '0',
    kc: '7',
    q: sourceText,
    tk: sM(sourceText)
  };

  const url = `https://translate.google.${translateOptions.tld}/translate_a/single`;

  const options = {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams(queryParams).toString()
  };

  return new Promise((resolve, reject) => {
    https
      .request(url, options, (resp) => {
        let data = '';

        resp.on('data', (chunk) => {
          data += chunk;
        });

        resp.on('end', () => {
          const result = normaliseResponse(JSON.parse(data));
          resolve(result?.text || sourceText);
        });
      })
      .on('error', (err) => {
        console.log('Error: ' + err.message);
        reject(err);
      })
      .end();
  });
};

```

**Comment by cjvnjde** [comment]
I tried to figure out how to make a request using POST. And it seems possible. This example worked for me.

```javascript
const traslateToEng = async (sourceText) => {
    const encodedValue = encodeURIComponent(`[[["MkEWBc","[[\\"${sourceText}\\",\\"ru\\",\\"en\\",true],[1]]",null,"generic"]]]`);
    return axios({
        method: 'POST',
        headers: {'content-type': 'application/x-www-form-urlencoded'},
        data: `f.req=${encodedValue}&`,
        url: 'https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?hl=en-US',
    })
};

traslateToEng('Привет').then((result) => {
    console.log(JSON.parse(result.data.replace(')]}\'', '').trim()));
});
```

But there is still a lot of work.  Сurrent functions don't work very well for this example.

**Comment by taishi55** [comment]
It looks perfect to me haha. 
What is the sM function doing in your current repo? I really wonder what it does

**Comment by cjvnjde** [comment]
sM generates necessary token. Here is the repo sM is based on. 
https://github.com/matheuss/google-translate-token

**Comment by cjvnjde** [comment]
I've updated the library. Try to use alpha version that uses POST requests. 

`npm install google-translate-api-browser@alpha`

I tested it with this example
https://github.com/cjvnjde/google-translate-api-browser/tree/v4.0.6-alpha/examples/server

But I'm not sure about the reliability of this version.

**Comment by taishi55** [comment]
Thank you for the update. I will look into that. Your reverse engineering skill is so talented. Could you teach me the part in detail? I will pay you $100 for the lesson.

**Comment by Asmedian** [comment]
> But I'm not sure about the reliability of this version.

![image](https://github.com/cjvnjde/google-translate-api-browser/assets/64973761/e6b961bf-b611-4ee0-848d-181f4fdf83a9)

Error when using in Node
`translate(string, {to: lang})
 .then(res => {
   console.log(res.text)
})
.catch(err => {
   console.error(err);
});`

**Comment by cjvnjde** [comment]
> > But I'm not sure about the reliability of this version.
> 
> ![image](https://user-images.githubusercontent.com/64973761/270395748-e6b961bf-b611-4ee0-848d-181f4fdf83a9.png)
> 
> Error when using in Node `translate(string, {to: lang}) .then(res => { console.log(res.text) }) .catch(err => { console.error(err); });`

Google has changed the structure of the response. In version 4.1 it should work.

Post requests should also work.
