### ISSUE TITLE
Proxy Support Please

### ISSUE THREAD

**Issue by Pevernow** [cjvnjde/google-translate-api-browser#23]
For some reason, I need to access Google through a proxy server.

Is there any way to translate text through an agent?

**Comment by cjvnjde** [comment]
For this case, you can use `createRequestBody` and `generateRequestUrl` to make requests; you can also use the `normaliseResponse` function to format responses. 
These functions allow you to modify requests as desired (including using proxies or something else) and dictate the way you make them, whether it's through axios, fetch, or https.

You can find an example [here](https://codesandbox.io/p/devbox/google-translate-api-node-custom-kr29rz?file=%2Findex.js%3A35%2C26)
