### ISSUE TITLE
CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by NyuBlara** [cjvnjde/google-translate-api-browser#37]
After attempting to use the package with the default CORS proxy URL (http://cors-anywhere.herokuapp.com/), and encountering a 403 error, I then attempted to use two separate proxy servers : [CorsProxy.io](https://corsproxy.io/) and [CORS.SH](https://proxy.cors.sh/).

With both of these servers, the package reports a `NetworkError`, and the underlying error is as follows : 

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [PROXY URL]/https://translate.google.com/_/TranslateWebserverUi/data/batchexecute. [...] (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```

For reference, the calling code is the following : 

```js
const response = await translate(translatedText, {
        to: nextLang,
        corsUrl: 'https://proxy.cors.sh/' // or https://corsproxy.io/
})
```

This seems to suggest that proper headers are not added to the POST request for proxy servers other than the default.

**Comment by cjvnjde** [comment]
Thanks for the ticket. I'll take a look at it over the weekend

**Comment by WilliamFalci** [comment]
@cjvnjde same issue here

**Comment by cjvnjde** [comment]
In version 4.3, it is now possible to include custom headers.

like so
```typescript
translate(text, { headers: { something: "something" } })
```
