### ISSUE TITLE
'BAD_NETWORK' for long text

### ISSUE THREAD

**Issue by raviraj16** [cjvnjde/google-translate-api-browser#4]
'BAD_NETWORK' alert shows while translating a long text. Also the console prints '414 (Request-URI Too Long)'.

**Comment by cjvnjde** [comment]
Google translate has a limit of 5,000 characters per request. Was your test longer than 5k characters?

**Comment by raviraj16** [comment]
Yes, you are right, my text is larger than the threshold limit.
