### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by hubingliang** [cjvnjde/google-translate-api-browser#6]
![image](https://user-images.githubusercontent.com/23694644/57307567-64bff900-7117-11e9-9d2f-cfb37be17012.png)

**Comment by cjvnjde** [comment]
Apparently Google translator has a limit of requests of 100,000 per day.

**Comment by cjvnjde** [comment]
Looks like a limitation of Heroku.

**Comment by HengjiaLi** [comment]
Hi, very nice application but I also run into this "429 too many requests" problem. Any solution for that?

**Comment by cjvnjde** [comment]
> 
> 
> Hi, very nice application but I also run into this "429 too many requests" problem. Any solution for that?

You can try to use self-hosted CORS server.
