### ISSUE TITLE
How to run in browser version ?

### ISSUE THREAD

**Issue by SylvainNZ** [cjvnjde/google-translate-api-browser#7]
Hi, could you provide some instruction on how to test the browser version ?
I downloaded all the files in the sample app to the same folder but when I run index.html I get the following error:

![browser version](https://user-images.githubusercontent.com/25375326/60748660-4b86dc00-9fe4-11e9-9f6a-152fffa4eef9.png)

Can I include google-translate-api-browser  without using Node ?

**Comment by SylvainNZ** [comment]
I managed to make a PowerShell script to use Google translate but still the JS can be handy for on the fly translation.

**Comment by cjvnjde** [comment]
The examples use bundler (parcel) because browsers don't support ES6 import/export. If you are using powershell to run example you need to run following commands "yarn install; yarn start".
You can't use it without some bundler because there are dependencies with npm modules.
